language: php
php:
   - 5.6
   - 7.0

before_script:
   - wget http://getcomposer.org/composer.phar
   - php composer.phar install --dev --no-interaction

script:
   - php vendor/bin/phpunit --whitelist src --test-suffix=.php --coverage-clover build/logs/clover.xml test

after_script:
   - travis_retry php coveralls -v

