language: php
php:
   - 7.0
   - 7.1

before_script:
   - travis_retry wget http://getcomposer.org/composer.phar
   - travis_retry php composer.phar install --dev --no-interaction

script:
   - php vendor/bin/phpunit --whitelist src --test-suffix=.php --coverage-clover build/logs/clover.xml test

after_script:
   - travis_retry php vendor/bin/coveralls -v

